// console.log(array1.length)
// console.log(array1);


// const myarr2=new Array(1,2,3);
// console.log(myarr2,"KKKKKKKKK")


// const newarr = []
// newarr.push("Hello","world")
// console.log(newarr);
// console.log(newarr.length);
// newarr.length = 6

// console.log(newarr.length);

// newarr[4]="Bye"
// console.log(newarr);

// for (let i in newarr){
//     console.log(newarr[i]);
// }

// Array methods

const array1 =['Asif','chaudhary','maddy']
// console.log(array1)

array1.push('Khan')
console.log(array1)
// array1.pop()

// array1.unshift(9)   // insert element at first index

// console.log(array1)

// array1.shift()   // remove first element
// console.log(array1.includes('Asif'))
// console.log(array1.indexOf('Asif'))

// const newarr = array1.join().split(',')
// console.log(newarr,typeof newarr,"JJJJ",newarr[0])

// Slice is use for slicing

const myn1=array1.slice(0,2)
console.log(myn1);
console.log(array1)


// Splice is use for cut element in new array

const myn2= array1.splice(1,3)
console.log(myn2)
console.log(array1)

